### ISSUE TITLE
Gradle 5 Support

### ISSUE THREAD

**Issue by benwatson528** [sedovalx/gradle-aspectj-binary#3]
This plugin doesn't work on Gradle 5 because:

```
Execution failed for task ':weaveClasses'
org.gradle.api.tasks.SourceSetOutput.getClassesDir()Ljava/io/File;
...
Caused by: java.lang.NoSuchMethodError: org.gradle.api.tasks.SourceSetOutput.getClassesDir()Ljava/io/File;
com.github.sedovalx.gradle.aspectj.AjcTask.compile(AjcTask.kt:45)
org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
```

This is because `SourceSetOutput.getClassesDir()` has been replaced in Gradle 5 with `getClassesDirs()` (see https://discuss.gradle.org/t/could-not-get-unknown-property-classesdir-for-main-classes-of-type-org-gradle-api-internal-tasks-defaultsourcesetoutput/30570).

I've tried playing around but I'm sadly not experienced enough with Kotlin, AspectJ or Gradle to fully resolve this issue. I got half way in a [PR](https://github.com/benwatson528/gradle-aspectj-binary/pull/1) that you might find useful, but the `AjcTask.kt` class still needs updating to replace the three calls to the deprecated `SourceSetOutput.getClassesDir()`.

Is there any chance of a new release to support Gradle 5?

**Comment by sedovalx** [comment]
Hi Ben,
I've added a bunch of commits to support Gradle 5 API and it works for me locally. But I... well, have troubles with Travis and Bintray that prevents me from publishing the new version. Spent some time trying to reincarnate the obsolete build but no luck yet. Here is the last build of the library https://travis-ci.org/sedovalx/gradle-aspectj-binary/builds/584127491 but I don't see the uploaded version in Bintray. Don't really have more time for this task for the next two weeks. Sorry about that. If you can manage with the code only - good, if you have any tips about how to publish in Bintray - great!

**Comment by benwatson528** [comment]
I really appreciate the effort, thanks! I'm normally a Nexus and Jenkins guy, but I'll have a play around and see if I can get anything to work. Thanks again!

**Comment by sedovalx** [comment]
Seems I finally found out how to achieve it. Will do in a few hours.

**Comment by sedovalx** [comment]
Done https://bintray.com/sedovalx/com.github.sedovalx/com.github.sedovalx.gradle-aspectj-binary/_latestVersion

**Comment by benwatson528** [comment]
I know you mention Java 7 compatibility in the README, but I don't think the plugin is compatible with Java 8 anymore. This is a bit surprising as Gradle 5 doesn't support Java 7.

In my Java 8, Gradle 5.6.1 project I have

```
weaveClasses.dependsOn compileJava
classes.dependsOn weaveClasses

weaveClasses {
    source = '1.8'
    target = '1.8'
    writeToLog = true
}
```

and get

```
org.aspectj.apache.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
        at org.aspectj.apache.bcel.classfile.Constant.readConstant(Constant.java:139)
        at org.aspectj.apache.bcel.classfile.ConstantPool.<init>(ConstantPool.java:98)
        at org.aspectj.apache.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:186)
        at org.aspectj.apache.bcel.classfile.ClassParser.parse(ClassParser.java:131)
        at org.aspectj.weaver.bcel.BcelWeaver.addAspectsFromJarFile(BcelWeaver.java:260)
        at org.aspectj.weaver.bcel.BcelWeaver.addLibraryJarFile(BcelWeaver.java:236)
        at org.aspectj.ajdt.internal.core.builder.AjBuildManager.initBcelWorld(AjBuildManager.java:874)
        at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:249)
        at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:185)
        at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:112)
        at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:60)
        at org.aspectj.tools.ajc.Main.run(Main.java:371)
        at com.github.sedovalx.gradle.aspectj.AjcTask.compile(AjcTask.kt:91)
...

1 fail\|abort                                                                                                                                                                                                                                                                                                                                                                :weaveClasses took 5618ms
```

The project successfully builds, but the AspectJ method logging doesn't work (I don't see any method logs, which makes sense given `:weaveClasses` fails). https://github.com/jcabi/jcabi-aspects/issues/257 suggests upgrading `aspectjtools` to `1.9.2`, but as you mention that would break Java 7 compatibility.

**Comment by sedovalx** [comment]
That's what happens when you do something in a hurry. As you may see in the `.travis.yml`, the plugin itself now builds with `openjdk8` which means you need at least jdk8 to compile a target project with the plugin. Still, the target version of the emitted bytecode can be 1.7. 

I have nothing against breaking jdk7 compatibility though. So, if you update the AspectJ version and try the result I will gladly accept the pull request. I will be unavailable for the next two weeks, hope you will manage :)
