### ISSUE TITLE
Adding custom Ajc task parameters?

### ISSUE THREAD

**Issue by jacjac3** [sedovalx/gradle-aspectj-binary#7]
Is there a way we can pass in an ajc parameter during the class weaving steps? I want to use the **proceedOnError** parameter for ajc.

Looks like most parameters are hardcoded here
https://github.com/sedovalx/gradle-aspectj-binary/blob/f10e23cae7d530756873e01e52247f609de276f4/plugin/src/main/kotlin/com/github/sedovalx/gradle/aspectj/AjcTask.kt#L62

Any hack or workarounds without forking the project?

Thanks

**Comment by sedovalx** [comment]
No, I don't see how to pass the parameter in without changing the plugin code. I would add something like `additionalAjcParams` List property to the plugin configuration `aspectjBinary {}` for that. Shouldn't be too hard. You may want to wait until I have spare time to return to this but I encourage you to make a pull request :)

**Comment by jacjac3** [comment]
PR created.

**Comment by sedovalx** [comment]
Thank you. Published `1.0.45` version with the related changes.

**Comment by jacjac3** [comment]
Thanks for the quick response!
